### ISSUE TITLE
Missing artifact io.datonis.sdk:aliot-sdk:jar:3.1

### ISSUE THREAD

**Issue by HarsukhVank** [Altizon/Aliot-SDK-Examples#1]
Importing the project in eclipse but Getting this error  : Missing artifact io.datonis.sdk:aliot-sdk:jar:3.1 

I tried to find it in maven repository but I didn't find it.

**Comment by rajesh-altizon** [comment]
Did you do:
mvn install:install-file -Dfile=lib/aliot-sdk-3.1.jar -DgroupId=io.datonis.sdk -DartifactId=aliot-sdk -Dversion=3.1 -Dpackaging=jar

**Comment by rajesh-altizon** [comment]
Here are the steps, please let me know if it does not work for you:
https://github.com/Altizon/Aliot-SDK-Examples/blob/master/java/README.md

**Comment by HarsukhVank** [comment]
Solution for me was I had to add aliotSDK jar to the project because aliotSDK was not found in Maven Repository.

**Comment by rajesh-altizon** [comment]
Yes, it is not available on the public github repository. So it needs to installed using mvn or added directly to classpath like you did.
Did the example work for you after you added it explicitly?

**Comment by HarsukhVank** [comment]
This is another problem I have faced
aliot.properties file : I had to put in root of the project otherwise it was not found by system. 

Now Example is working for me

**Comment by rajesh-altizon** [comment]
Ok thanks harsukh. Actually, it all works seemlessly if you use mvn and follow corresponding steps.
But, it seems not everyone may be using mvn. I will add documentation so that people can use it directly by importing it as a project. thanks

**Comment by HarsukhVank** [comment]
I did import project using maven in eclipse but it was not able find aliotSDK, Error was given in pom.xml  then I added jar to lib folder.

**Comment by rajesh-altizon** [comment]
Ok, thanks for your feedback harsukh
