### ISSUE TITLE
InstructionHandler : Bidirectional connection 

### ISSUE THREAD

**Issue by HarsukhVank** [Altizon/Aliot-SDK-Examples#2]
I have for loop of 5  for transmit data events. data sent for 5 times successfully 

and rule created which will send every time response to the code 

Got reply only once :  Received instruction for thing: d2faat792f from Datonis: {"instruction":{"temp":"50"}}

How come not for five times??

**Comment by rajesh-altizon** [comment]
Hello Harsukh,

Can you please let me know the rule key of your rule (part of the URL)?
I will take a look. Rules usually have a waiting period associated with them. So once it is triggered, it will not trigger again for that period of time (even if the condition for that rule is satisfied)

Regards,
Rajesh

**Comment by HarsukhVank** [comment]
Query 1)
 Rule : Interval is  1 sec, Condition is temperature is >=10 
 Passing value : 10, 20, 30, 40, 50 by for loop as an interval of 1 sec (Thread sleep) and "bulk_transmit": false,  "protocol": "mqtts . 

Getting response for  only 1 time instead of 5. 

Frequently getting this : Connection to Datonis MQTT server is lost. Attempting to connect again...
and connection is establishing with thing  like following 

"Connection to Datonis MQTT server is lost. Attempting to connect again...
2016-07-12 12:56:41,571 INFO  [Gateway-Monitor] GatewayMonitor - Sent heart beats for the Things
364822 [Gateway-Monitor] INFO io.datonis.sdk.GatewayMonitor  - Sent heart beats for the Things
2016-07-12 12:56:41,970 INFO  [Handshake-Consumer-pool-thread-1] GatewayMessageConsumer - Transmitted Message in 399 ms : {"thing_key":"d2faat792f","timestamp":1468308401571}
365221 [Handshake-Consumer-pool-thread-1] INFO io.datonis.sdk.GatewayMessageConsumer  - Transmitted Message in 399 ms : {"thing_key":"d2faat792f","timestamp":1468308401571}
Connection to Datonis MQTT server is lost. Attempting to connect again...
Connection to Datonis MQTT server is lost. Attempting to connect again...
2016-07-12 12:58:41,563 INFO  [Gateway-Monitor] GatewayMonitor - Sent heart beats for the Things
484814 [Gateway-Monitor] INFO io.datonis.sdk.GatewayMonitor  - Sent heart beats for the Things
2016-07-12 12:58:41,961 INFO  [Handshake-Consumer-pool-thread-1] GatewayMessageConsumer - Transmitted Message in 398 ms : {"thing_key":"d2faat792f","timestamp":1468308521563}
485212 [Handshake-Consumer-pool-thread-1] INFO io.datonis.sdk.GatewayMessageConsumer  - Transmitted Message in 398 ms : {"thing_key":"d2faat792f","timestamp":1468308521563}
Connection to Datonis MQTT server is lost. Attempting to connect again...
"

#########################################################################
Query 2) 
I am not calling - agent.stopGateway();
If I close this It will give exception : Thread Interruption and Handshake will be interrupted

**Comment by rajesh-altizon** [comment]
Hi Harsukh,

Re #Query 1: Can you try using mqtt (instead of mqtts) for now.
Re #Query 2: That is OK. Those errors are expected. agent.stopGateway() only needs to be called when your gateway is supposed to shutdown

Regards,
Rajesh

**Comment by HarsukhVank** [comment]
For Query 1)
I changed protocol to mqtt, But result is same.
####
Another Approaches 
1 :  Interval of 30 seconds between events in for loop (Transmit Data)
If I do this :  Thread.currentThread().sleep(30000) - All events responses come (5 events : 5 responses) 

#####

2:  Interval of 30 seconds between events in for loop (Transmit Data)
If I do this :  Thread.currentThread().sleep(30000) - 6 events responses come (10 events : 6 responses)

####

3:  Interval of 1 second between events in for loop (Transmit Data)
If I do this :  Thread.currentThread().sleep(1000) - 1 event response comes (10 events : 1 response)

####

4:  Interval of 20 seconds between events in for loop (Transmit Data)
If I do this :  Thread.currentThread().sleep(20000) - 7 events responses come (10 events : 7 responses)

####

But I want to send data every second (instead of 30 Seconds interval). Then response comes for only once.

#####
#####

For Query 2)

" Connection to Datonis MQTT server is lost. Attempting to connect again... "

When all events sent successfully this happens because of I haven't closed the gateway. And If I close the gateway after all events send then How can I get responses
I am not sure when will be my last response so that I can call this : agent.stopGateway();

**Comment by rajesh-altizon** [comment]
Ok Harsukh, 

Let me follow your steps and check.

Regards,
Rajesh

**Comment by rajesh-altizon** [comment]
Hi Harsukh,

Yes, so that is a limitation of our platform as of now - The rules are evaluated every 30 seconds (for performance reasons).
So even if there were potentially 5 datapoints that could trigger the rule at that point in time, it will trigger only once.
However, we do acknowledge the fact that it is a limitation and it will be addressed in our upcoming release.
We can keep this ticket open till then.

Also, the MQTT server reconnecting failures will be resolved with this as well.

Regards,
Rajesh

**Comment by Apoorv903** [comment]
i m using python_agent of yours, but its showing error of "zipImport : can't find module com.altizon.aliot.gateway_config " and if i extract it and then try to use it then i got bad magic number error, i feel there is error of python version i m using python3.6
please provide updated guide or tutorial file content is also differ from documentation 
![capture](https://user-images.githubusercontent.com/22665720/27021637-5d012672-4f67-11e7-8b42-90956ac64f51.PNG)

**Comment by thakur00mayank** [comment]
Hi Harsukh,

Closing this issue as we have removed the limit of evaluating the rules every 30 seconds.
