### ISSUE TITLE
java.io.FileNotFoundException: aliot.properties (No such file or directory) in Android 

### ISSUE THREAD

**Issue by HarsukhVank** [Altizon/Aliot-SDK-Examples#3]
I am able to run java project successfully. 

But I when I try to add those in Android Project, 

Null value for this  System.getProperty("aliot.properties")

I have tried to put aliot.properties in every folder of the project and also in every drive in my computer but still not able find it. 

@rajesh-altizon, Any idea what is happening here ?

**Comment by rajesh-altizon** [comment]
Hi Harsukh, 

I understand that you are doing an anrdoid project, so you cannot pass system properties as JVM options. But you could do one thing. There must be some sort of a main program that you must be using.
In that, you could do System.setProperty("aliot.properties", "path to your properties file"), right before you create the gateway object.

Regards
Rajesh

**Comment by rajesh-altizon** [comment]
Also, Of course you will need to create/generate that file at some location on the device and then pass the path to the System.setProperty

**Comment by HarsukhVank** [comment]
@rajesh-altizon, 
Thank you.
I followed your advice.

And the solution is for Android: 
1) Add aliot.properties file into assets folder 
2) Copy aliot.properties file from assets folder to phone internal storage.
3) Set System.setProperty();

**Comment by rajesh-altizon** [comment]
Thanks Harsukh
