### ISSUE TITLE
Unable to send data to datonis dashboard using python

### ISSUE THREAD

**Issue by ApoorvVarma** [Altizon/Aliot-SDK-Examples#5]
i m using python_agent of yours, but its showing error of "zipImport : can't find module com.altizon.aliot.gateway_config " and if i extract it and then try to use it then i got bad magic number error, i feel there is error of python version i m using python3.6
 content is also differ from documentation please provide updated guide or tutorial file 
thank you
![capture](https://user-images.githubusercontent.com/22665720/27021692-a6944a26-4f67-11e7-8c95-0f8885bca48a.PNG)

**Comment by rajesh-altizon** [comment]
Hello Apoorv,
Thanks for your query. Kindly please create a ticket at http://support.altizon.com
Our support team will get in touch with you

Regards,
Rajesh

**Comment by ApoorvVarma** [comment]
ok thank you Rajesh for response
