### ISSUE TITLE
'GatewayConfig' is not defined

### ISSUE THREAD

**Issue by conradneilands** [Altizon/Aliot-SDK-Examples#6]
This is all I can ever get from the unmodified example:
Starting aliot agent
Traceback (most recent call last):
  File "sample.py", line 107, in <module>
    main()
  File "sample.py", line 47, in main
    gateway_config = GatewayConfig('72f2a8322fca8dc4ttt321t49f83at58f8t78t54', 'cf5a1eba58756db5ta741t7a25ca686eba3acdaf', 'http')
NameError: global name 'GatewayConfig' is not defined

I have even tried unzipping the compiled python code and importing each of the .pyc files separately, successful import but same error

python3 will refuse to import the files due to magic number errors

**Comment by rajesh-altizon** [comment]
We have faced this issue earlier. We will be posting complete set of python files shortly.

**Comment by thakur00mayank** [comment]
We have posted the complete set of python files with python2 as well as python3 support.
Here is the new repo for [python sdk](https://github.com/Altizon/datonis-edge-sdk-python).
