### ISSUE TITLE
thing metric does not support doubles / decimals

### ISSUE THREAD

**Issue by conradneilands** [Altizon/Aliot-SDK-Examples#8]
This is broken:
Sending Data: {"timestamp":1501554831000,"thing_key":"298fb67211","data":{"LAeq1m":"63.0"},"waypoint":[-32.8802282,151.7216769]}
Response code: 422
Error 300027 : Data sent in the event does not match the metrics associated with the thing/sensor.

This is not:
Sending Data: {"timestamp":1501554974000,"thing_key":"t3fa43d97d","data":{"LAeq1m":66},"waypoint":[-32.8802282,151.7216769]}
Response code: 200

The Metric selected in datonis.io is "Number". Documentation says all number types are accepted

**Comment by ChandrachudIngale** [comment]
Hi Conrad,

Please check the JSON format for your metric LAeq1m, if its defined of NUMBER type its getting transmitted as String from your agent. Please omit the quotes " " and change it from **"LAeq1m":"63.0"** to "LAeq1m":63.0

**Comment by conradneilands** [comment]
Im not adding the quotes as far as i can tell these are being added
automatically.
The 63.0 comes directly from a variable. This variable is set from a serial
port string which i have coverted to a float using the to_f function

**Comment by rajesh-altizon** [comment]
Hi Conrad,

which SDK are you using? Python or Ruby?

Regards,
Rajesh

**Comment by rajesh-altizon** [comment]
I believe its Ruby. Let me check

**Comment by conradneilands** [comment]
Fixed it. The to_f function wasn't applied to the right variable.
Thanks for your help

**Comment by rajesh-altizon** [comment]
Great, thanks for letting us know. 
Just FYI, we are going to host these samples code blocks on separate repositories (one per language).
Will be deprecating this repository soon

Regards,
Rajesh
